# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-16 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='unversity',
            new_name='university',
        ),
    ]
